### ISSUE TITLE
Not writing M*D15A2 geotiff files

### ISSUE THREAD

**Issue by nishanbh** [lbusett/MODIStsp#60]
using R version 3.2.2 on Platform: x86_64-w64-mingw32/x64 (64-bit)
The tiff files for 8-day LAI/FPAR (LAI_1km and FPAR_1km) are not created on the output folders (i.e., folders FAPR and LAI are empty). It does write Tiff files for QC bits.

**Comment by lbusett** [comment]
Thanks for reporting this. Will have a look ASAP. 

Can you tell us if you are using the `master` or the `devel` branch ?

**Comment by nishanbh** [comment]
I used the default one and DID NOT specify ref='devel' during installation. 
MODIS level -6 products such as 8-day LST, 8-day surface reflectances are working just fine.

**Comment by ggranga** [comment]
The error was due to a problem in managing multiple nodata values. As you can notice from the [product description](https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table/mod15a2), fpar and lai have a range of values associated with nodata (249-255): this caused the error.
Commit fb05d3b4fd029495a829ee06da7b67c413a906ed should have partially fixed it: now the layer is produced, but nodata values are not recognised (you have to know than values between 249 and 255 are nodata).
This problem will fully fixed in future (it requires more code editing, since GDAL does not manage multiple nodata for the same band).
