### ISSUE TITLE
Drop in download speed

### ISSUE THREAD

**Issue by lbusett** [lbusett/MODIStsp#65]
From HG issue reported  here, https://github.com/lbusett/MODIStsp/issues/64
> 
> With the hotfix version download speed was reduced dramatically and I got the error
> Warning  #messages:
> 1: running command '"aria2c"' had status 1
> 
> I have just downloaded the "devel" version and I am still getting the same warning message
> 1: running command '"aria2c"' had status 1

**Comment by lbusett** [comment]
@hgiche 

I opened a new issue. This is strange. We'll check it next week.

**Comment by lbusett** [comment]
Hi Helene, 
   can you tell me if you're using `ftp` or `http` download ? 

Lorenzo

**Comment by hgiche** [comment]
Hi Lorenzo - I am using http.

**Comment by lbusett** [comment]
On linux, I'm not seeing changes in speed nor warnings - will check on windows ASAP.

**Comment by ggranga** [comment]
Hi Helene,
I made some tests on this product both on Linux and Windows, without being able to reproduce this issue: download speed resulted high (normal) both with aria2c and wget. Could this issue be related to NASA server's problems, or to problems with the connection to it? Maybe check it again during next days.

Ps. recently we updated the ProdOpts file in order to shorten product names: after this update, already processed products are re-processed, since names changed. This would not have consequences on download speed, since hdf file names did not change, but could increase total processing time.

**Comment by hgiche** [comment]
Thanks Lorenzo for looking into this issue.  For one year of data (NDVI, VI quality, composite day of the year, pixel reliability, land/water flag) it is taking me approx. 16 hours and with the error message "running command '"aria2c"' had status 1"
I will try download the data on a different day later this week.

**Comment by lbusett** [comment]
Hi Helene,
   
     I committed a new version in `devel`: https://github.com/lbusett/MODIStsp/commit/efbf1b469e7518ffc8a7ec6d9922242d6a5c228f

It should solve the issue on `running command '"aria2c"' had status 1`, and also some other problems on download (hopefully, it should also improve speed in some cases) . Try it out if you wish. 

By the way: download speed from NASA server is greatly variable. As a rule of thumb, however, the highest speed should be obtained with `ftp`  download, with `aria2c` option activated. 

Lorenzo

**Comment by hgiche** [comment]
Thanks Lorenzo.
