### ISSUE TITLE
Installing Issues

### ISSUE THREAD

**Issue by Marcy-S** [lbusett/MODIStsp#83]
Hi,
Novice user here - I'm trying to install MODIStsp following the vignette instructions. I'm working on a MAC 10.12.5, and am running R 3.4.0 - I'm not sure that these will work because I am coming up against a number of missing dependency packages from which I cannot access via CRAN on R. If I go directly to Cran there are versions but not for the most recent Macs, I download the older ones  and then try to install via install.packages ("XX", lib="~/XXX"), they appear to install. Similarly, I can't access MODIStsp via the cran directory on r - so I do the above action to install and it does say its installed, but when I try to then start the GUI - using library("MODIStsp") it says that it can't find the package. Where is my error and/or should I remove the version of r and try an older one?

Thanks

**Comment by lbusett** [comment]
Hi, 

   last time I checked on a MAC I was able to install without problems. However, I saw now that the package build from CRAN seems to be failing for R 3.4 due to missing gWidgetsRGtk2 package.
 (https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/MODIStsp-00check.html).

Could you try first of all to install gWidgetsRGtk2, following these instructions: 

    install.packages("gWidgetsRGtk2")
    library(gWidgetsRGtk2)

Upon loading gWidgetsRGtk2 , an error window will probably appear. This signals that library “GTK+” is not yet installed on your system or is not on your PATH. To install itpress “OK”. A new window dialog window will appear, asking if you want to install “GTK+”. Select “Install GTK” and then “OK” . Windows will download and install the GTK+ library. When it finishes, the RSession should be restarted and you should be ready to go !

In case RStudio doesn’t automatically restart or continuously asks to install GTK+ again, kill it form “Task Manager” (or restart the R session from RStudio “Session” menu), reload RStudio and the try to reload gWidgetsRGtk2. If it loads correctly, you should be ready to go.

Now install the devel version of MODIStsp using: 

    library(devtools)
    devtools::install_github("hadley/devtools")     
    devtools::install_github("lbusett/MODIStsp")

HTH,

Lorenzo

**Comment by Marcy-S** [comment]
I think it worked (I had to do a couple of installs from tgz. for things
like cairodevice) but I am able to open the GUI so now I'll just start
testing to see if I can do all the functions.

Thanks so much!

**Comment by lbusett** [comment]
Glad it helped. Let us know if you still have problems.
