### ISSUE TITLE
Can't download burned area products

### ISSUE THREAD

**Issue by bmarcos** [lbusett/MODIStsp#97]
Hi,

I can't download burned area products from FTP. It gives the following error:

> Error in strsplit(full_dirs, "/") : non-character argument

Also, I noticed that only Collection 5 seems to be available to be selected, either using the GUI or command line interface. Both Collection 5 and Collection 5.1 for MCD45A1 product, as well as the new Collection 6 MCD64A1 product, should be available for download through FTP (https://e4ftl01.cr.usgs.gov/MOTA/).

Thanks.

**Comment by lbusett** [comment]
Hi, 
 
   thanks for signaling this. Will have a look asap.  Can you please tell us if you are working on Window or Linux or MacOs, and maybe save the options you use for the processing and send us the JSON file ?

**Comment by lbusett** [comment]
By the way: Are you able to access the link you sent from a browser? On my connection, it is currently unreachable.

**Comment by bmarcos** [comment]
Hi,

I am currently on Ubuntu Linux 16.04.

Neither 'ftp' nor 'offline' options would work. The 'http' option did work for a few files, until the server went down. Still, only MCD45A1.V005 is available, not MCD45A1.V051 or MCD64A1.V006.

I downloaded MCD45A1.V051 via normal FTP and tried to run MODIStsp with the 'offline' option to see if it would preprocess the files, but it did not recognise them.

I was able to access the link, but since after I posted last time, the servers appear to be down. Hopefully, it is temporary.

Thanks.


[mcd45a1.json.zip](https://github.com/lbusett/MODIStsp/files/1492076/mcd45a1.json.zip)

**Comment by lbusett** [comment]
Hi, 

    concerning the V006 and V051 versions, they were introduced recently and are not currently supported. 

Also , the V005 and V051 versions are not apparently available anymor on FTP, while they are availbale on http. 

Therefore: Currently, you can download only the V005 using http. Using ftp will not work since the product is no longer there. 

I'll try to make a quick fix so add support at least for  V006 (I don't think it is useful to add also the v051 version. What do you think? ) 

Using the offline mode will also not work on v006 or v051 files until I add the support. 

I'd be however interested in knowing if you have problems also with v005 download over http. . 

Lorenzo

**Comment by bmarcos** [comment]
Hi,

You can access both v051 and v006 through FTP here:

> https://e4ftl01.cr.usgs.gov/MOTA/MCD45A1.051/
> https://e4ftl01.cr.usgs.gov/MOTA/MCD64A1.006/

Probably, the addresses have changed. But I managed to download v051 for one tile, all available dates, so it seems to be working now.

If it is not too much trouble, it would be nice to have both v051 and v006 available, since v051 is an improved version of v005, while v006 is an entirely new product (different algorithms, different product code, etc.).

Thanks a lot!

**Comment by lbusett** [comment]
Hi, 

  I did a quick fix to add support for MCD64A1, and change the http download address for MCD45A1 so that v051 is used instead than v 05. You can install the patched version using: 

`devtools::install_github("lbusett/MODIStsp", ref = "feature/mdc45a1_v006_support")`

**Please remove your current MODIStsp installation beforehand.**

You should find a new product in the selection list, plus downloading v5 should downloade v51 hdf files. 

Could you test it and let me know if it works of for you? If so, I will later include the fix in the stable versions.

**Comment by bmarcos** [comment]
Hi,

I have precessed both MCD45A1.V051 and MCD64A1.V006 with the patched version and everything seems to be working well. Thanks a lot!

I have realized there's a new / alternative FTP server for downloading all three Burned Area products:

> ftp://ba1.geog.umd.edu/

You need to put in a username and password to get access, but it is more for statistical purposes, because the username and password seems to be the same for everyone. I don't know if this helps, or if it is viable to put MODIStsp working with this ftp server, but I thought you should know about it.

Cheers!

**Comment by lbusett** [comment]
Fixed and pulled on devel on: 

https://github.com/lbusett/MODIStsp/commit/ef13e35d3aee1acce6981b7429d0d392184a549e

Now both V005 and V051 can be accessed, + the new MCD64A1 product is available.
